import {
  img_1,
  img_10,
  img_11,
  img_12,
  img_13,
  img_14,
  img_15,
  img_16,
  img_17,
  img_18,
  img_19,
  img_2,
  img_20,
  img_21,
  img_22,
  img_23,
  img_24,
  img_3,
  img_4,
  img_5,
  img_6,
  img_7,
  img_8,
  img_9,
} from "../../../assets/img";

const products = [
  {
    id: 1,
    category: "mobile",
    badge_id: 1,
    image: img_1,
    star_value: 5,
    review_count: 789,
    stock_status: true,
    description: "TOZO T6 True Wireless Earbuds Bluetooth Headphon...",
    price: 70,
  },
  {
    id: 2,
    category: "mobile",
    badge_id: null,
    image: img_2,
    star_value: 5,
    review_count: 536,
    stock_status: true,
    description: "Samsung Electronics Samsung Galexy S21 5G",
    price: 2300,
  },
  {
    id: 3,
    category: "tv",
    badge_id: 2,
    image: img_3,
    star_value: 5,
    review_count: 423,
    stock_status: true,
    description: "Amazon Basics High-Speed HDMI Cable (18 Gbps, 4K/6...",
    price: 360,
  },
  {
    id: 4,
    category: "ear",
    badge_id: null,
    image: img_4,
    star_value: 4,
    review_count: 816,
    stock_status: true,
    description: "Portable Wshing Machine, 11lbs capacity Model 18NMF...",
    price: 80,
  },
  {
    id: 5,
    category: "drone",
    badge_id: null,
    image: img_5,
    star_value: 5,
    review_count: 647,
    stock_status: true,
    description: "Wired Over-Ear Gaming Headphones with USB",
    price: 1500,
  },
  {
    id: 6,
    category: "tv",
    badge_id: 4,
    image: img_6,
    star_value: 4,
    review_count: 877,
    stock_status: true,
    description: "Polaroid 57-Inch Photo/Video Tripod with Deluxe Tripod Ca...",
    price: 1600,
    disc_price: 1200,
    disc_percentage: 25,
  },
  {
    id: 7,
    category: "tv",
    badge_id: null,
    image: img_1,
    star_value: 5,
    review_count: 877,
    stock_status: true,
    description: "Dell Optiplex 7000x7480 All-in-One Computer Monitor",
    price: 250,
  },
  {
    id: 8,
    category: "mobile",
    badge_id: 3,
    image: img_8,
    star_value: 5,
    review_count: 583,
    stock_status: true,
    description: "4K UHD LED Smart TV with Chromecast Built-in",
    price: 220,
  },
  {
    id: 9,
    category: "ear",
    badge_id: 2,
    image: img_9,
    star_value: 4,
    review_count: 360,
    stock_status: false,
    description: "Amazon Basics High-Speed HDMI Cable (18 Gbps, 4K/6...",
    price: 360,
  },
  {
    id: 10,
    category: "ear",
    badge_id: null,
    image: img_10,
    star_value: 5,
    review_count: 798,
    stock_status: true,
    description: "Portable Wshing Machine, 11lbs capacity Model 18NMF...",
    price: 80,
  },
  {
    id: 11,
    category: "keyboard",
    badge_id: 1,
    image: img_11,
    star_value: 5,
    review_count: 600,
    stock_status: true,
    description: "TOZO T6 True Wireless Earbuds Bluetooth Headphon...",
    price: 70,
  },
  {
    id: 12,
    category: "printer",
    badge_id: null,
    image: img_12,
    star_value: 5,
    review_count: 583,
    stock_status: true,
    description: "Dell Optiplex 7000x7480 All-in-One Computer Monitor",
    price: 250,
  },
  {
    id: 13,
    category: "camera",
    badge_id: null,
    image: img_13,
    star_value: 4,
    review_count: 740,
    stock_status: true,
    description: "Samsung Electronics Samsung Galexy S21 5G",
    price: 2300,
  },
  {
    id: 14,
    category: "camera",
    badge_id: 3,
    image: img_14,
    star_value: 4,
    review_count: 556,
    stock_status: false,
    description: "Dell Optiplex 7000x7480 All-in-One Computer Monitor",
    price: 220,
  },
  {
    id: 15,
    category: "printer",
    badge_id: null,
    image: img_15,
    star_value: 4,
    review_count: 536,
    stock_status: true,
    description: "Wired Over-Ear Gaming Headphones with USB",
    price: 1500,
  },
  {
    id: 16,
    category: "washing_machine",
    badge_id: 4,
    image: img_16,
    star_value: 4,
    review_count: 423,
    description: "Polaroid 57-Inch Photo/Video Tripod with Deluxe Tripod Ca...",
    price: 1600,
    stock_status: false,
    disc_price: 1200,
    disc_percentage: 25,
  },
  {
    id: 17,
    category: "tv",
    badge_id: 1,
    image: img_17,
    star_value: 5,
    review_count: 738,
    stock_status: true,
    description: "TOZO T6 True Wireless Earbuds Bluetooth Headphon...",
    price: 70,
  },
  {
    id: 18,
    category: "mobile",
    badge_id: null,
    image: img_18,
    star_value: 5,
    review_count: 536,
    stock_status: true,
    description: "Samsung Electronics Samsung Galexy S21 5G",
    price: 2300,
  },
  {
    id: 19,
    category: "ac",
    badge_id: 2,
    image: img_19,
    star_value: 5,
    review_count: 423,
    stock_status: false,
    description: "Amazon Basics High-Speed HDMI Cable (18 Gbps, 4K/6...",
    price: 360,
  },
  {
    id: 20,
    category: "headphone",
    badge_id: null,
    image: img_20,
    star_value: 4,
    review_count: 816,
    stock_status: true,
    description: "Portable Wshing Machine, 11lbs capacity Model 18NMF...",
    price: 80,
  },
  {
    id: 21,
    category: "mobile",
    badge_id: 2,
    image: img_21,
    star_value: 4,
    review_count: 994,
    stock_status: true,
    description: "Amazon Basics High-Speed HDMI Cable (18 Gbps, 4K/6...",
    price: 360,
  },
  {
    id: 22,
    category: "laptop",
    badge_id: null,
    image: img_22,
    star_value: 5,
    review_count: 492,
    stock_status: true,
    description: "Dell Optiplex 7000x7480 All-in-One Computer Monitor",
    price: 250,
  },
  {
    id: 23,
    category: "phone",
    badge_id: 4,
    image: img_23,
    star_value: 5,
    review_count: 798,
    description: "Portable Wshing Machine, 11lbs capacity Model 18NMF...",
    price: 124,
    disc_price: 80,
    stock_status: true,
    disc_percentage: 25,
  },
  {
    id: 24,
    category: "laptop",
    badge_id: 1,
    image: img_24,
    star_value: 5,
    review_count: 600,
    stock_status: false,
    description: "TOZO T6 True Wireless Earbuds Bluetooth Headphon...",
    price: 70,
  },
];

const badge_value = {
  1: { val: "hot", color: "#EE5858" },
  2: { val: "Best Deals", color: "#2DA5F3" },
  3: { val: "sale", color: "#2DB224" },
  4: { val: "discount", color: "#EFD33D" },
};

export { products, badge_value };
